DROP DATABASE IF EXISTS jobsearcher_db;
CREATE DATABASE jobsearcher_db;
USE jobsearcher_db;
CREATE TABLE  (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
);
CREATE TABLE role (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
);
CREATE TABLE employee (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
);